var json = [
    {
        "id": 1,
        "pasta": "1",
        "qtdFotos": 5,
        "nome": "H50FT",
        "marca": "HYSTER",
        "valor": "R$ 49.900,00",
        "ano": 2010,
        "torre": "3,8mts Duplex",
        "capacidade": "2500 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado e pintura nova, possui 4º via."        
    },
    {
        "id": 2,
        "pasta": "2",
        "qtdFotos": 3,
        "nome": "H50FT",
        "marca": "HYSTER",
        "valor": "R$ 62.000,00",
        "ano": 2013,
        "torre": "3,8mts Duplex",
        "capacidade": "2500 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado e pintura nova, motor novo."        
    },
    {
        "id": 3,
        "pasta": "3",
        "qtdFotos": 4,
        "nome": "H50FT",
        "marca": "HYSTER",
        "valor": "R$ 54.900,00",
        "ano": 2011,
        "torre": "3,8mts Duplex",
        "capacidade": "2500 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado e pintura nova, possui 4º via."        
    },
    {
        "id": 4,
        "pasta": "4",
        "qtdFotos": 4,
        "nome": "H60XM",
        "marca": "HYSTER",
        "valor": "R$ 44.000,00",
        "ano": 2004,
        "torre": "3,8mts Duplex",
        "capacidade": "3000 KG",
        "comb": "DIESEL",
        "observacao": "Equipamento todo revisado, DIESEL, 60% mais economia que GLP."        
    },
    {
        "id": 5,
        "pasta": "5",
        "qtdFotos": 4,
        "nome": "H50XM",
        "marca": "HYSTER",
        "valor": "R$ 37.000,00",
        "ano": 2000,
        "torre": "3,8mts Duplex",
        "capacidade": "2500 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado, pronto para operar, simples de manutenção."        
    },
    {
        "id": 6,
        "pasta": "6",
        "qtdFotos": 5,
        "nome": "50VX",
        "marca": "YALE",
        "valor": "R$ 54.900,00",
        "ano": 2010,
        "torre": "4,8mts Duplex",
        "capacidade": "2500 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado, pintura nova, torre alta."        
    },
    {
        "id": 7,
        "pasta": "7",
        "qtdFotos": 4,
        "nome": "CMP18",
        "marca": "CLARK",
        "valor": "R$ 35.900,00",
        "ano": 2009,
        "torre": "4,7mts Triplex",
        "capacidade": "1800 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado, torre alta, pronta para trabalhar."        
    },
    {
        "id": 8,
        "pasta": "8",
        "qtdFotos": 3,
        "nome": "H155XL",
        "marca": "HYSTER",
        "valor": "R$ 35.900,00",
        "ano": 1998,
        "torre": "5,2mts Duplex",
        "capacidade": "7000 KG",
        "comb": "GLP",
        "observacao": "Equipamento todo revisado, com deslocador lateral, pneus novos."        
    }
]